-- WITH dates_data AS (
--     SELECT
--         DISTINCT
--         event_date AS date_id,
--         EXTRACT(YEAR FROM event_date) AS year,
--         EXTRACT(MONTH FROM event_date) AS month,
--         EXTRACT(DAY FROM event_date) AS day,
--         EXTRACT(DOW FROM event_date) AS weekday
--     FROM {{ ref('stg_store_events') }}
-- )
-- SELECT * FROM dates_data
